### ISSUE TITLE
[Question] When will new languages be added?

### ISSUE THREAD

**Issue by gork7777** [AdguardTeam/KnowledgeBaseVPN#106]
When will Turkish language be added as an example? It would be nice to include languages that are mostly translated so we can look at the translations.

**Comment by gork7777** [comment]
Any news?

**Comment by ameshkov** [comment]
@el-termikael could you please handle this? I reckon there's a list of translated languages, we'll need the full list.

**Comment by el-termikael** [comment]
@gork7777 could you kindly translate a few remaining strings? https://crowdin.com/translate/adguard-vpn-knowledge-base/all/en-tr?filter=basic&value=0
Currently AdGuard VPN Knowledge base is 99% translated to Turkish, we'll add it to the website soon

**Comment by el-termikael** [comment]
@ameshkov apart from in-house languages, it's also translated to Czech: https://crowdin.com/project/adguard-vpn-knowledge-base

**Comment by gork7777** [comment]
@el-termikael Done, thanks for handle these!

**Comment by anastasiia-fedotova** [comment]
@gork7777 We've recently added new languages to the AdGuard VPN Knowledge base. Articles can now be read in Turkish, Portuguese (Brazilian), and Czech. Many thanks for your help and support.
