### ISSUE TITLE
Add a detailed guide for the use of AdGuard VPN on routers

### ISSUE THREAD

**Issue by kyjhoz-mikfip-goXci0** [AdguardTeam/KnowledgeBaseVPN#150]
For the life of me, I can't get AdGuard VPN working on my router. I detailed guide would be great.

**Comment by anastasiia-fedotova** [comment]
Hello! Did you follow the steps outlined in these instructions https://adguard-vpn.com/en/router/overview.html?

**Comment by anastasiia-fedotova** [comment]
Oh, and here are detailed instructions published in the Knowledge base https://adguard-vpn.com/kb/general/set-up-adguard-vpn-on-your-router/
