### ISSUE TITLE
The "AdGuard VPN for routers" setup guide(s) lack info on its (lack of?) support for ASUS routers.

### ISSUE THREAD

**Issue by DandelionSprout** [AdguardTeam/KnowledgeBaseVPN#188]
*Long story short:* It turns out it's not just enough *per se* for a router to support IKE2 IPsec to support "AdGuard VPN for routers", but that there's caveats that make it impossible to use on ASUS routers.

**Problem:** I checked https://adguard-vpn.com/en/blog/adguard-vpn-for-routers.html and https://adguard-vpn.com/en/apple-tv/overview.html in detail as a result of https://github.com/AdguardTeam/AdGuardVPNForiOS/issues/369, and there are some missing details regarding ASUS routers, including, but not limited to:
- The setup guides say to turn on "VPN Client". ASUS routers only have "VPN Server" and "VPN Fusion", the latter being ASUS' term for "VPN Client" in recent years for unknown reasons.
- "VPN Server" supports IKEv2, but only for certificate-based exports on PC and possibly Android. "VPN Fusion", which is the one needed for most non-PC devices, does *not* support IKEv2.

**Proposed fixes:** 
- In https://adguard-vpn.com/en/blog/adguard-vpn-for-routers.html, change:
- - *"This feature requires an AdGuard VPN subscription and IKEv2/IPsec support. More protocols will be added in the future."* ↓
- - *"This feature requires an AdGuard VPN subscription and IKEv2/IPsec support in the router's "VPN Client" (**not** "VPN Server") settings. More protocols will be added in the future."*
- Add something like *"If the router's internal VPN settings has an option to enter a Pre-shared Key, you're likely in the wrong settings menu. Only manual imports of VPN settings on a PC or Android device would need a Pre-shared Key."*

**Test environment:**
- Router: ASUS RT-AX89X
- Router firmware version: 3.0.0.4.388_32407-gb7814fc
- AdGuard VPN subscription: Paid, and the router is activated as a device (although the AdGuard online account settings for the device claims *"We don’t see any activity on your network. Please check your router settings and network connection"*

**Images**
<details><summary>What turned out to have been the wrong settings menu in ASUS routers:</summary>

![image](https://github.com/AdguardTeam/KnowledgeBaseVPN/assets/22780683/10a9fad3-e377-433e-a139-c18e3528c57b)
</details>

<details><summary>What turned out to be the correct menu but which somehow has fewer settings:</summary>

![image](https://github.com/AdguardTeam/KnowledgeBaseVPN/assets/22780683/db05bb1f-fc6e-495b-b609-7b5f59d7f57d)
</details>

**Comment by TS6ix2GaH3q679h5** [comment]
Interestingly, my older ASUS router does in fact refer to it as a "VPN Client" mode so I wonder if this change was recent. 

<img width="837" alt="image" src="https://github.com/user-attachments/assets/e58689e8-2753-4192-b282-95c4ee0cf99c">

Sadly it doesn't matter: like for you, mine doesn't support IKEv2 in client mode either.

**Comment by emeritaacuity0u** [comment]
As above for the FRITZ!Box routers.

**Comment by el-termikael** [comment]
the issue was mentioned in #198 by mistake, this setup guide will be updated soon

**Comment by puglieri** [comment]
The article was updated. Thanks for your insights, they were really helpful!
