### ISSUE TITLE
Update about description for this repo

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/KnowledgeBaseVPN#38]
Very minor, but the about description for this repo needs to be fixed so it mentions AdGuard VPN instead of AdGuard DNS.

<img width="471" alt="image" src="https://user-images.githubusercontent.com/65204836/188113614-95b884a4-b925-496d-8762-42328943ac56.png">

<img width="447" alt="image" src="https://user-images.githubusercontent.com/65204836/188113682-065c8e37-1fc2-4748-bde1-80c3d097697c.png">

**Comment by el-termikael** [comment]
Hey @planet0,
Thanks for noticing! Now it's fixed: https://uploads.adguard.org/el.termikael27w7l.png
