### ISSUE TITLE
Broken image

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/KnowledgeBaseVPN#90]
After step 5, there is a broken image with a blue question mark.

![DFDD0647-494E-487A-BABC-7DA0112A123D](https://user-images.githubusercontent.com/95468948/218722337-73de20ea-af10-4a60-af7d-599213626907.png)

https://adguard-vpn.com/kb/adguard-vpn-for-mac/installation/

**Comment by el-termikael** [comment]
@jslawler please check if the problem is fixed
I can see the image
